# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
