# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-14 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=999)),
                ('priority', models.CharField(choices=[(2, 'HIGH'), (1, 'MEDIUM'), (0, 'LOW')], default='MEDIUM', max_length=10)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
        ),
    ]
