# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=10)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greeting.List')),
            ],
        ),
    ]
