# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170728_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
